# Source: jx-verify/templates/release.yaml
apiVersion: jenkins.io/v1
kind: Release
metadata:
  creationTimestamp: "2021-02-15T16:34:42Z"
  deletionTimestamp: null
  name: 'jx-verify-0.0.64'
  namespace: jx-staging
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
spec:
  commits:
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: noreply@github.com
        name: GitHub
      message: 'chore: fix pipeline order'
      sha: 58f2ee5c17def9cda4a7f5ef98a074cb0786e3e6
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        chore: regen docs
      sha: f71dac34c0bcde5de0021c99e2bf6ac8c1433afa
    - author:
        email: james.strachan@gmail.com
        name: James Strachan
      branch: master
      committer:
        email: james.strachan@gmail.com
        name: James Strachan
      message: |
        chore: lets add a step to verify k8s context
      sha: f48fa0bdd8157983249b6a45136ebb22cfec63c8
  gitHttpUrl: https://github.com/jenkins-x/jx-verify
  gitOwner: jenkins-x
  gitRepository: jx-verify
  name: 'jx-verify'
  version: 0.0.64
status: {}
